#pragma once

#include <SDL3/SDL_scancode.h>

// Printable keys
#define LM_KEY_SPACE              SDL_SCANCODE_SPACE
#define LM_KEY_APOSTROPHE         SDL_SCANCODE_APOSTROPHE
#define LM_KEY_COMMA              SDL_SCANCODE_COMMA
#define LM_KEY_MINUS              SDL_SCANCODE_MINUS
#define LM_KEY_PERIOD             SDL_SCANCODE_PERIOD
#define LM_KEY_SLASH              SDL_SCANCODE_SLASH
#define LM_KEY_0                  SDL_SCANCODE_0
#define LM_KEY_1                  SDL_SCANCODE_1
#define LM_KEY_2                  SDL_SCANCODE_2
#define LM_KEY_3                  SDL_SCANCODE_3
#define LM_KEY_4                  SDL_SCANCODE_4
#define LM_KEY_5                  SDL_SCANCODE_5
#define LM_KEY_6                  SDL_SCANCODE_6
#define LM_KEY_7                  SDL_SCANCODE_7
#define LM_KEY_8                  SDL_SCANCODE_8
#define LM_KEY_9                  SDL_SCANCODE_9
#define LM_KEY_SEMICOLON          SDL_SCANCODE_SEMICOLON
#define LM_KEY_EQUAL              SDL_SCANCODE_EQUALS
#define LM_KEY_A                  SDL_SCANCODE_A
#define LM_KEY_B                  SDL_SCANCODE_B
#define LM_KEY_C                  SDL_SCANCODE_C
#define LM_KEY_D                  SDL_SCANCODE_D
#define LM_KEY_E                  SDL_SCANCODE_E
#define LM_KEY_F                  SDL_SCANCODE_F
#define LM_KEY_G                  SDL_SCANCODE_G
#define LM_KEY_H                  SDL_SCANCODE_H
#define LM_KEY_I                  SDL_SCANCODE_I
#define LM_KEY_J                  SDL_SCANCODE_J
#define LM_KEY_K                  SDL_SCANCODE_K
#define LM_KEY_L                  SDL_SCANCODE_L
#define LM_KEY_M                  SDL_SCANCODE_M
#define LM_KEY_N                  SDL_SCANCODE_N
#define LM_KEY_O                  SDL_SCANCODE_O
#define LM_KEY_P                  SDL_SCANCODE_P
#define LM_KEY_Q                  SDL_SCANCODE_Q
#define LM_KEY_R                  SDL_SCANCODE_R
#define LM_KEY_S                  SDL_SCANCODE_S
#define LM_KEY_T                  SDL_SCANCODE_T
#define LM_KEY_U                  SDL_SCANCODE_U
#define LM_KEY_V                  SDL_SCANCODE_V
#define LM_KEY_W                  SDL_SCANCODE_W
#define LM_KEY_X                  SDL_SCANCODE_X
#define LM_KEY_Y                  SDL_SCANCODE_Y
#define LM_KEY_Z                  SDL_SCANCODE_Z
#define LM_KEY_LEFT_BRACKET       SDL_SCANCODE_LEFTBRACKET
#define LM_KEY_BACKSLASH          SDL_SCANCODE_BACKSLASH
#define LM_KEY_RIGHT_BRACKET      SDL_SCANCODE_RIGHTBRACKET
#define LM_KEY_GRAVE_ACCENT       SDL_SCANCODE_GRAVE
#define LM_KEY_WORLD_1            SDL_SCANCODE_INTERNATIONAL1
#define LM_KEY_WORLD_2            SDL_SCANCODE_INTERNATIONAL2

/* Function keys */
#define LM_KEY_ESCAPE             SDL_SCANCODE_ESCAPE
#define LM_KEY_ENTER              SDL_SCANCODE_RETURN
#define LM_KEY_TAB                SDL_SCANCODE_TAB
#define LM_KEY_BACKSPACE          SDL_SCANCODE_BACKSPACE
#define LM_KEY_INSERT             SDL_SCANCODE_INSERT
#define LM_KEY_DELETE             SDL_SCANCODE_DELETE
#define LM_KEY_RIGHT              SDL_SCANCODE_RIGHT
#define LM_KEY_LEFT               SDL_SCANCODE_LEFT
#define LM_KEY_DOWN               SDL_SCANCODE_DOWN
#define LM_KEY_UP                 SDL_SCANCODE_UP
#define LM_KEY_PAGE_UP            SDL_SCANCODE_PAGEUP
#define LM_KEY_PAGE_DOWN          SDL_SCANCODE_PAGEDOWN
#define LM_KEY_HOME               SDL_SCANCODE_HOME
#define LM_KEY_END                SDL_SCANCODE_END
#define LM_KEY_CAPS_LOCK          SDL_SCANCODE_CAPSLOCK
#define LM_KEY_SCROLL_LOCK        SDL_SCANCODE_SCROLLLOCK
#define LM_KEY_NUM_LOCK           SDL_SCANCODE_NUMLOCKCLEAR
#define LM_KEY_PRINT_SCREEN       SDL_SCANCODE_PRINTSCREEN
#define LM_KEY_PAUSE              SDL_SCANCODE_PAUSE
#define LM_KEY_F1                 SDL_SCANCODE_F1
#define LM_KEY_F2                 SDL_SCANCODE_F2
#define LM_KEY_F3                 SDL_SCANCODE_F3
#define LM_KEY_F4                 SDL_SCANCODE_F4
#define LM_KEY_F5                 SDL_SCANCODE_F5
#define LM_KEY_F6                 SDL_SCANCODE_F6
#define LM_KEY_F7                 SDL_SCANCODE_F7
#define LM_KEY_F8                 SDL_SCANCODE_F8
#define LM_KEY_F9                 SDL_SCANCODE_F9
#define LM_KEY_F10                SDL_SCANCODE_F10
#define LM_KEY_F11                SDL_SCANCODE_F11
#define LM_KEY_F12                SDL_SCANCODE_F12
#define LM_KEY_F13                SDL_SCANCODE_F13
#define LM_KEY_F14                SDL_SCANCODE_F14
#define LM_KEY_F15                SDL_SCANCODE_F15
#define LM_KEY_F16                SDL_SCANCODE_F16
#define LM_KEY_F17                SDL_SCANCODE_F17
#define LM_KEY_F18                SDL_SCANCODE_F18
#define LM_KEY_F19                SDL_SCANCODE_F19
#define LM_KEY_F20                SDL_SCANCODE_F20
#define LM_KEY_F21                SDL_SCANCODE_F21
#define LM_KEY_F22                SDL_SCANCODE_F22
#define LM_KEY_F23                SDL_SCANCODE_F23
#define LM_KEY_F24                SDL_SCANCODE_F24
#define LM_KEY_F25                SDL_SCANCODE_F24  // SDL only goes to F24
#define LM_KEY_KP_0               SDL_SCANCODE_KP_0
#define LM_KEY_KP_1               SDL_SCANCODE_KP_1
#define LM_KEY_KP_2               SDL_SCANCODE_KP_2
#define LM_KEY_KP_3               SDL_SCANCODE_KP_3
#define LM_KEY_KP_4               SDL_SCANCODE_KP_4
#define LM_KEY_KP_5               SDL_SCANCODE_KP_5
#define LM_KEY_KP_6               SDL_SCANCODE_KP_6
#define LM_KEY_KP_7               SDL_SCANCODE_KP_7
#define LM_KEY_KP_8               SDL_SCANCODE_KP_8
#define LM_KEY_KP_9               SDL_SCANCODE_KP_9
#define LM_KEY_KP_DECIMAL         SDL_SCANCODE_KP_PERIOD
#define LM_KEY_KP_DIVIDE          SDL_SCANCODE_KP_DIVIDE
#define LM_KEY_KP_MULTIPLY        SDL_SCANCODE_KP_MULTIPLY
#define LM_KEY_KP_SUBTRACT        SDL_SCANCODE_KP_MINUS
#define LM_KEY_KP_ADD             SDL_SCANCODE_KP_PLUS
#define LM_KEY_KP_ENTER           SDL_SCANCODE_KP_ENTER
#define LM_KEY_KP_EQUAL           SDL_SCANCODE_KP_EQUALS
#define LM_KEY_LEFT_SHIFT         SDL_SCANCODE_LSHIFT
#define LM_KEY_LEFT_CONTROL       SDL_SCANCODE_LCTRL
#define LM_KEY_LEFT_ALT           SDL_SCANCODE_LALT
#define LM_KEY_LEFT_SUPER         SDL_SCANCODE_LGUI
#define LM_KEY_RIGHT_SHIFT        SDL_SCANCODE_RSHIFT
#define LM_KEY_RIGHT_CONTROL      SDL_SCANCODE_RCTRL
#define LM_KEY_RIGHT_ALT          SDL_SCANCODE_RALT
#define LM_KEY_RIGHT_SUPER        SDL_SCANCODE_RGUI
#define LM_KEY_MENU               SDL_SCANCODE_MENU